### ISSUE TITLE
options.path does not work correctly on windows

### ISSUE THREAD

**Issue by junosuarez** [jonschlinkert/parse-git-config#1]
On Windows, calling `git.sync({cwd: 'c:\', path: 'c:\Users\jden\.gitconfig'})` is resolving the path to `c:\c:\Users\Jason\.gitconfig`

Expected:

`c:\Users\Jason\.gitconfig`

**Comment by junosuarez** [comment]
Thanks for merging #2! Could you please publish on npm?

**Comment by jonschlinkert** [comment]
done, I published 0.3.1 yesterday :)
