### ISSUE TITLE
overwrites third or more push URL

### ISSUE THREAD

**Issue by isysd** [jonschlinkert/parse-git-config#10]
Lets say you have remote `a` with push URLs `1`, `2`, and `3`. The record in `.git/config` would look like this:

```
[remote "a"]
        url = 1
        fetch = +refs/heads/*:refs/remotes/a/*
        pushurl = 2
        pushurl = 3
```

This library will ignore one of the pushurl keys. Logically, any greater number of push urls will also be discarded.

**Comment by jonschlinkert** [comment]
you're saying that `pushurl` is currently a string, but should be an array?

**Comment by isysd** [comment]
I'm saying that `pushurl` is treated like an array bit git, but is stored in the string format, if considered as strict `ini`.

**Comment by isysd** [comment]
I decided to patch a lower-level library, which could be used to replace this one.

https://github.com/nfer/git-config-ini/pull/1

This has a unit test, so you can see what the expected format and behavior is.

**Comment by jonschlinkert** [comment]
very lame of you, thanks for wasting my time with an issue.
