### ISSUE TITLE
Support 'include' directives

### ISSUE THREAD

**Issue by silverwind** [jonschlinkert/parse-git-config#5]
The [include](https://git-scm.com/docs/git-config#_includes) directive is useful to include another git configuration file in the current one. For example, I use it to store private information like access tokens in it, which allows me to commit my [.gitconfig](https://github.com/silverwind/dotfiles/blob/9b6f0536d264aacd809a54314dc12ed5d49263df/.gitconfig#L1) to a public repository.

Not that `~` is resolved in the include path, so applying [untildify](https://github.com/sindresorhus/untildify) on the path will be wise.

**Comment by jonschlinkert** [comment]
To clarify, you want the parsed object to include other the other git configs (which are specified using `include`)? I like the idea, how about if we make that optional?

edit: could you paste an example of the configs you use (obviously with fake information) so that I can use that for unit tests? thanks!

**Comment by silverwind** [comment]
Examples (The values in the 2nd file are placeholder, not sure if git like them like that):

[`.gitconfig`](https://github.com/silverwind/dotfiles/raw/9b6f0536d264aacd809a54314dc12ed5d49263df/.gitconfig)
[`.gitconfig.local`](https://raw.githubusercontent.com/silverwind/dotfiles/9b6f0536d264aacd809a54314dc12ed5d49263df/.gitconfig.local)

> how about if we make that optional?

git parses included files by default, so I think this module should do. I'd see some value in having a option to disable parsing them, so a option to disable might make sense.

**Comment by jonschlinkert** [comment]
perfect! thanks!

edit: 

> git parses included files by default, so I think this module should do. I'd see some value in having a option to disable parsing them, so a option to disable might make sense.

True, but this module probably shouldn't follow the same rules, given that it's more likely that private information could be accidentally included and shared.

**Comment by silverwind** [comment]
Sure, I'm fine with a opt-in too.

**Comment by jonschlinkert** [comment]
I just pushed up [a branch](https://github.com/jonschlinkert/parse-git-config/tree/includes) if you'd like to test it locally before I publish tomorrow. 

edit: actually let me update a few things, then I'll ping you here again

**Comment by jonschlinkert** [comment]
k, I pushed up more changes. I'll add a changelog with more details, but in summary:

- adds promise support
- adds support for `include`
- renamed `.keys` method name to `.expandKeys`

**Comment by silverwind** [comment]
Looking good. During testing, I attempted to trick the parser with conflicting options in the included file, but my testing showed that it parses conflicts exactly like git does. Nice work!

**Comment by jonschlinkert** [comment]
Sorry, I completely forgot to come back and merge! I made the mistake of viewing this on my phone, then it disappeared from my new issues list, so I didn't see it when I logged on. publishing now!

**Comment by jonschlinkert** [comment]
done, published and released as 2.0.

> I attempted to trick the parser with conflicting options in the included file, but my testing showed that it parses conflicts exactly like git does. Nice work!

Thanks! I implemented the logic to follow the spec described in the link you provided, so that the config properties would be merged in the correct order. Glad it worked!
